# Generated by Django 5.0.6 on 2024-06-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_doubt_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="paused",
            field=models.BooleanField(default=False),
        ),
    ]
